### ISSUE TITLE
As a student, I want to book a lesson so that I can attend lesson.

### ISSUE THREAD

**Issue by arifjehoh** [ht100xht22/monolith#3]
# Scenario: Book, a guitar lesson at school

## Prerequisite

- [x] #5
- [x] Level instruments have a level date and time, instrument.
- [x] #7

## Given
The school provided a list of available lessons for my guitar with level and date, and time.

- [x] List of available lessons.
- [x] Filter on instrument, level, date, and time.

## When
I have chosen to lesson to book

## Then
I will be given that the booking has been made and a request is in progress to match the teacher.

- [x] #9

**Comment by Nilfal** [comment]
Submit a form of the chosen lesson with the student profile.
 
Alt: 

Add List as a variable in Lesson to reg Student id. 
For individual lessons list length = 1 
Group & esambels append all students' ids to the list.

**Comment by Nilfal** [comment]
Is Bookable = students.lenght == max_students
